### ISSUE TITLE
Some Modification base on Mike's email

### ISSUE THREAD

**Issue by rhshah** [msk-access/sequence_qc#12]
Thanks very much for preparing this. Just a couple of minor suggestions for the graphs:

1. Top graph: Change the y-axis label to “ Alt Count / (Alt Count + Ref Count) x 10^6 “ and remove the mu
2. Label as Duplex consensus (assuming that’s what’s in the calculation)
3. Noise Positions graph: Change the y-axis label to “ Alt Count / Total Count “. Can remove the genomic positions from the x-axis label since there is not enough space to show all of them, and it’s not so informative.

**Comment by ionox0** [comment]
changes are in master branch
