### ISSUE TITLE
noise calculation gives higher estimate than old method

### ISSUE THREAD

**Issue by ionox0** [msk-access/sequence_qc#2]
![Screen Shot 2020-05-16 at 2 02 20 PM](https://user-images.githubusercontent.com/6385646/82126937-06901200-977e-11ea-947c-a08a757b0332.png)

**Comment by ionox0** [comment]
While the relative heights of the bars are the same, we seem to be getting higher values than previously

This could be because insertions / deletions are being included
- for this we should investigate whether we want to include these in the calculation, or see if we get closer to the old values without them being included

It could also be due to the fact that we are using the Pool A bed file, which includes MSI regions
- for this we should create a good positions bed file

**Comment by rhshah** [comment]
@ionox0  thanks for working on this. It is encouraging that we are close to the original values. I think first you should use the good position pool A bed file and calculate noise two ways for the same sample :
- SNVs
- Indels 

Hopefully, that will give us a better estimate.

**Comment by ionox0** [comment]
![Screen Shot 2020-05-18 at 5 05 07 PM](https://user-images.githubusercontent.com/6385646/82259536-c40b3880-9929-11ea-99d5-fe1bdc790505.png)
yes much closer after removing MSI regions

will update with SNV / indel difference

**Comment by ionox0** [comment]
A few things have gotten this much closer to waltz / calculate_noise.sh 

1. Re-ran waltz with the new Pool A bedfile that doesn't have the MSI regions
2. Re-ran with waltz 3.2 where previously it was 2.0
3. Using pysamstats instead of raw pysam
4. Using truncate = 0 parameter, which leaves out regions that are part of reads that only partially overlap the bedfile
5. Set min_mapq = 1 similar to waltz setting
6. Set min_basq = 1
7. Set ignore_overlaps = True (this combined with # 6 means that overlapping reads aren't double-counted) https://github.com/pysam-developers/pysam/issues/834
