### ISSUE TITLE
add documentation / readme

### ISSUE THREAD

**Issue by ionox0** [msk-access/sequence_qc#3]
Will we use `.rst` through sphinx / readthedocs, or will we use GitBook?

**Comment by rhshah** [comment]
It's up to you I am ok either ways

**Comment by ionox0** [comment]
Ok I'll probably go with GitBook, would you be able to create that for me? Thank you!

**Comment by rhshah** [comment]
@ionox0  can we have command in the README to run this. Also can we consolidate all the version, pypi has 0.1.17, conda has 0.1.15 and release has 0.1.12

**Comment by ionox0** [comment]
ok, I've updated both pypi and anaconda to 0.1.18 and included Usage section in the readme

**Comment by rhshah** [comment]
Thank you
